### ISSUE TITLE
Error report

### ISSUE THREAD

**Issue by imogen-rickert** [ironhack-edu/data_mid_bootcamp_project_regression#1]
7. Create calculated field year_built_bins for the column year_built by creating buckets as follows, for houses built between **1900 and 2000** - category A, for houses built between 2000 and 2010 - category B, and for houses built between **1900 and 2000** - category C.

**Comment by siandav** [comment]
@sandrabosk fyi

**Comment by ironhack-edu** [comment]
Fixed. Thanks Sian
